import React from "react";
import {
  GraduationCap, Award, BookOpen, FlaskConical,
  Handshake, Star, Shield, FolderOpen,
} from "lucide-react";
import type { Category, ProfileData } from "./types";

export const mapLecturerToCategories = (lecturer: any): Category[] => {
  return [
    {
      id: "kualifikasi",
      label: "Kualifikasi",
      icon: <GraduationCap className="w-5 h-5" />,
      color: "#0284C7",
      subCategories: [
        {
          id: "pendidikan-formal",
          label: "Pendidikan Formal",
          entity: "Pendidikan Formal",
          columns: ["No", "Perguruan Tinggi", "Program Studi", "Gelar Akademik", "Tahun Lulus"],
          rows: (lecturer.educations || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.university || "-",
            item.program || "-",
            item.degree || "-",
            item.graduation_year || "-",
          ]),
          visible: true,
        },
        {
          id: "diklat",
          label: "Diklat",
          entity: "Riwayat Diklat",
          columns: ["No", "Nama Diklat", "Penyelenggara", "Tahun", "Durasi"],
          rows: (lecturer.diklats || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.name || "-",
            item.organizer || "-",
            item.year || "-",
            item.duration || "-",
          ]),
          visible: true,
        },
        {
          id: "riwayat-pekerjaan",
          label: "Riwayat Pekerjaan",
          entity: "Riwayat Pekerjaan",
          columns: ["No", "Institusi", "Jabatan", "Mulai", "Selesai"],
          rows: (lecturer.employments || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.institution || "-",
            item.position || "-",
            item.start_date || "-",
            item.end_date || "Sekarang",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "kompetensi",
      label: "Kompetensi",
      icon: <Award className="w-5 h-5" />,
      color: "#16A34A",
      subCategories: [
        {
          id: "sertifikasi",
          label: "Sertifikasi",
          entity: "Riwayat Sertifikasi",
          columns: ["No", "Nama Sertifikasi", "Bidang Studi", "Tahun", "Nomor SK"],
          rows: (lecturer.certifications || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.name || "-",
            item.field_of_study || "-",
            item.year || "-",
            item.sk_number || "-",
          ]),
          visible: true,
        },
        {
          id: "tes",
          label: "Tes",
          entity: "Riwayat Tes",
          columns: ["No", "Nama Tes", "Penyelenggara", "Tahun", "Skor"],
          rows: (lecturer.competencyTests || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.name || "-",
            item.organizer || "-",
            item.year || "-",
            item.score || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "pelaksanaan-pendidikan",
      label: "Pelaksanaan Pendidikan",
      icon: <BookOpen className="w-5 h-5" />,
      color: "#0369A1",
      subCategories: [
        {
          id: "pengajaran",
          label: "Pengajaran",
          entity: "Pengajaran",
          columns: ["No", "Mata Kuliah", "Tahun", "Semester", "SKS", "Jumlah Mahasiswa"],
          rows: (lecturer.teachings || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.course_name || "-",
            item.year || "-",
            item.semester || "-",
            item.credits || "-",
            item.total_students || "-",
          ]),
          visible: true,
        },
        {
          id: "bimbingan-mahasiswa",
          label: "Bimbingan Mahasiswa",
          entity: "Bimbingan Mahasiswa",
          columns: ["No", "Nama Mahasiswa", "NIM", "Tingkat", "Judul", "Status"],
          rows: (lecturer.studentSupervisions || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.student_name || "-",
            item.nim || "-",
            item.level || "-",
            item.title || "-",
            item.status || "-",
          ]),
          visible: true,
        },
        {
          id: "penguji",
          label: "Penguji",
          entity: "Penguji",
          columns: ["No", "Nama Mahasiswa", "NIM", "Peran", "Tanggal Ujian"],
          rows: (lecturer.studentExaminations || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.student_name || "-",
            item.nim || "-",
            item.role || "-",
            item.exam_date || "-",
          ]),
          visible: true,
        },
        {
          id: "bahan-ajar",
          label: "Bahan Ajar",
          entity: "Bahan Ajar",
          columns: ["No", "Judul", "Jenis", "Tahun", "Penerbit/Platform"],
          rows: (lecturer.teachingMaterials || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.type || "-",
            item.year || "-",
            item.publisher || "-",
          ]),
          visible: true,
        },
        {
          id: "pengembangan-mahasiswa",
          label: "Pengembangan Mahasiswa",
          entity: "Pengembangan Mahasiswa",
          columns: ["No", "Kegiatan", "Peran", "Tahun", "Keterangan"],
          rows: (lecturer.studentDevelopments || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.activity_name || "-",
            item.role || "-",
            item.year || "-",
            item.description || "-",
          ]),
          visible: true,
        },
        {
          id: "visiting-scientist",
          label: "Visiting Scientist",
          entity: "Visiting Scientist",
          columns: ["No", "Institusi", "Tahun", "Lama (Bulan)"],
          rows: (lecturer.visitingScientists || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.institution || "-",
            item.year || "-",
            item.duration_months || "-",
          ]),
          visible: true,
        },
        {
          id: "detasering",
          label: "Detasering",
          entity: "Detasering",
          columns: ["No", "Perguruan Tinggi Sasaran", "Kategori Kegiatan", "No SK", "Tanggal SK"],
          rows: (lecturer.detaserings || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.target_university || "-",
            item.activity_category || "-",
            item.assignment_decree_number || "-",
            item.decree_date || "-",
          ]),
          visible: true,
        },
        {
          id: "orasi-ilmiah",
          label: "Orasi Ilmiah",
          entity: "Orasi Ilmiah",
          columns: ["No", "Kategori", "Judul Makalah", "Penyelenggara", "Tanggal"],
          rows: (lecturer.academicOrations || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.activity_category || "-",
            item.paper_title || "-",
            item.organizer || "-",
            item.activity_date || "-",
          ]),
          visible: true,
        },
        {
          id: "pembimbingan-dosen",
          label: "Pembimbingan Dosen",
          entity: "Pembimbingan Dosen",
          columns: ["No", "Nama Dosen Dibimbing", "Mulai", "Selesai"],
          rows: (lecturer.lectureMentorings || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.mentor_name || "-",
            item.start_date || "-",
            item.end_date || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "pelaksanaan-penelitian",
      label: "Pelaksanaan Penelitian",
      icon: <FlaskConical className="w-5 h-5" />,
      color: "#B45309",
      subCategories: [
        {
          id: "penelitian",
          label: "Penelitian",
          entity: "Penelitian",
          columns: ["No", "Judul Penelitian", "Peran", "Tahun", "Dana"],
          rows: (lecturer.research || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.role || "-",
            item.year || "-",
            item.funding || "-",
          ]),
          visible: true,
        },
        {
          id: "publikasi-karya",
          label: "Publikasi Karya",
          entity: "Publikasi Karya",
          columns: ["No", "Judul", "Jenis", "Penerbit/Venue", "Tahun"],
          rows: (lecturer.publications || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.type || "-",
            item.venue || "-",
            item.year || "-",
          ]),
          visible: true,
        },
        {
          id: "hki",
          label: "HKI",
          entity: "HKI",
          columns: ["No", "Judul Invensi", "Jenis", "Tahun", "Status"],
          rows: (lecturer.hkis || lecturer.hki || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.type || "-",
            item.year || "-",
            item.status || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "pelaksanaan-pengabdian",
      label: "Pelaksanaan Pengabdian",
      icon: <Handshake className="w-5 h-5" />,
      color: "#065F46",
      subCategories: [
        {
          id: "pengabdian",
          label: "Pengabdian",
          entity: "Pengabdian",
          columns: ["No", "Judul", "Peran", "Mitra", "Tahun"],
          rows: (lecturer.communityServices || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.role || "-",
            item.partner || "-",
            item.year || "-",
          ]),
          visible: true,
        },
        {
          id: "jabatan-struktural",
          label: "Jabatan Struktural",
          entity: "Jabatan Struktural",
          columns: ["No", "Nama Jabatan", "No SK", "Mulai", "Selesai"],
          rows: (lecturer.structuralPositions || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.position_name || "-",
            item.decree_number || "-",
            item.start_date || "-",
            item.end_date || "Sekarang",
          ]),
          visible: true,
        },
        {
          id: "pembicara",
          label: "Pembicara",
          entity: "Pembicara",
          columns: ["No", "Judul Kegiatan", "Peran", "Penyelenggara", "Tahun"],
          rows: (lecturer.speakers || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.event_title || "-",
            item.role || "-",
            item.organizer || "-",
            item.year || "-",
          ]),
          visible: true,
        },
        {
          id: "pengelola-jurnal",
          label: "Pengelola Jurnal",
          entity: "Pengelola Jurnal",
          columns: ["No", "Nama Jurnal", "Peran", "No SK", "Tanggal SK"],
          rows: (lecturer.journalManagers || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.journal_name || "-",
            item.role || "-",
            item.decree_number || "-",
            item.effective_date || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "penunjang",
      label: "Penunjang",
      icon: <Star className="w-5 h-5" />,
      color: "#9D174D",
      subCategories: [
        {
          id: "beasiswa",
          label: "Beasiswa",
          entity: "Beasiswa",
          columns: ["No", "Nama Beasiswa", "Pemberi", "Tahun"],
          rows: (lecturer.scholarships || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.name || "-",
            item.giver || "-",
            item.year || "-",
          ]),
          visible: true,
        },
        {
          id: "anggota-profesi",
          label: "Anggota Profesi",
          entity: "Riwayat Anggota Profesi",
          columns: ["No", "Nama Organisasi", "Tingkat", "Tahun Bergabung"],
          rows: (lecturer.professionalMemberships || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.organization_name || "-",
            item.level || "-",
            item.year_joined || "-",
          ]),
          visible: true,
        },
        {
          id: "kegiatan-lain",
          label: "Kegiatan Lain",
          entity: "Kegiatan Penunjang Lain",
          columns: ["No", "Nama Kegiatan", "Penyelenggara", "Peran", "Tahun"],
          rows: (lecturer.otherSupportingActivities || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.activity_name || "-",
            item.organizing_institution || "-",
            item.role || "-",
            item.start_date || "-",
          ]),
          visible: true,
        },
        {
          id: "tugas-tambahan",
          label: "Tugas Tambahan",
          entity: "Tugas Tambahan",
          columns: ["No", "Tugas Tambahan", "Unit Kerja", "Institusi", "Mulai"],
          rows: (lecturer.additionalTasks || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.additional_task || "-",
            item.work_unit || "-",
            item.institution || "-",
            item.start_date || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "reward",
      label: "Reward",
      icon: <Shield className="w-5 h-5" />,
      color: "#000000ff",
      subCategories: [
        {
          id: "penghargaan",
          label: "Penghargaan",
          entity: "Penghargaan",
          columns: ["No", "Nama Penghargaan", "Pemberi", "Tahun", "Tingkat"],
          rows: (lecturer.awards || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.name || "-",
            item.giver || "-",
            item.year || "-",
            item.level || "-",
          ]),
          visible: true,
        },
        {
          id: "kesejahteraan",
          label: "Kesejahteraan",
          entity: "Kesejahteraan",
          columns: ["No", "Jenis Kesejahteraan", "Nama", "Tahun", "Penyelenggara"],
          rows: (lecturer.welfares || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.type || "-",
            item.name || "-",
            item.year || "-",
            item.provider || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "data-dokumen",
      label: "Data Dokumen",
      icon: <FolderOpen className="w-5 h-5" />,
      color: "#000000ff",
      subCategories: [
        {
          id: "riwayat-dokumen-pribadi",
          label: "Riwayat Dokumen Pribadi",
          entity: "Riwayat Dokumen Pribadi",
          columns: ["No", "Jenis Dokumen", "Nomor Dokumen", "Masa Berlaku"],
          rows: (lecturer.identities || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.type || "-",
            item.number || "-",
            item.valid_until || "-",
          ]),
          visible: true,
        },
      ],
    },
  ];
};

export const mapLecturerToProfileData = (lecturer: any): ProfileData => {
  return {
    name: `${lecturer.title_prefix || ''} ${lecturer.name} ${lecturer.title_suffix || ''}`.trim(),
    imageUrl: lecturer.photo_url || "https://ui-avatars.com/api/?name=" + encodeURIComponent(lecturer.name) + "&background=F3F4F6&color=4B5563",
    university: "Universitas Udayana",
    program: lecturer.faculty || "Fakultas MIPA",
    SiwadaId: lecturer.nidn || lecturer.nip || "-",
    tags: [lecturer.study_program || "Informatika"],
    metrics: { 
      sintaOverall: lecturer.sinta_score_total?.toString() || "0", 
      sinta3Yr: lecturer.sinta_score_3yr?.toString() || "0", 
      scopusHIndex: "0", 
      wosHIndex: "0" 
    },
    activities: [], 
    publications: (lecturer.publications || []).map((pub: any) => ({
      id: pub.id,
      title: pub.title,
      venue: pub.venue || pub.publisher,
      year: parseInt(pub.year || pub.publish_year || new Date().getFullYear()), 
      authorOrder: "1 of 1", 
      type: pub.type || "Journal Article", 
      citations: pub.citation_count || 0,
    })),
  };
};
