import React from "react";
import {
  GraduationCap, Award, BookOpen, FlaskConical,
  Handshake, Star, Shield, FolderOpen,
} from "lucide-react";
import type { Category, ProfileData } from "./types";

export const mapLecturerToCategories = (lecturer: any): Category[] => {
  return [
    {
      id: "kualifikasi",
      label: "Kualifikasi",
      icon: <GraduationCap className="w-5 h-5" />,
      color: "#0284C7",
      subCategories: [
        {
          id: "pendidikan-formal",
          label: "Pendidikan Formal",
          entity: "Pendidikan Formal",
          columns: ["No", "Jenjang", "Perguruan Tinggi", "Program Studi", "Tahun Lulus"],
          rows: (lecturer.educations || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.level || "-",
            item.university || "-",
            item.study_program || "-",
            item.graduation_year || "-",
          ]),
          visible: true,
        },
        {
          id: "diklat",
          label: "Diklat",
          entity: "Riwayat Diklat",
          columns: ["No", "Nama Diklat", "Jenis Diklat", "Penyelenggara", "Tahun"],
          rows: (lecturer.diklats || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.training_name || "-",
            item.training_type || "-",
            item.organizer || "-",
            item.year || "-",
          ]),
          visible: true,
        },
        {
          id: "riwayat-pekerjaan",
          label: "Riwayat Pekerjaan",
          entity: "Riwayat Pekerjaan",
          columns: ["No", "No. SK CPNS", "Tanggal SK CPNS", "Golongan/Pangkat", "Status Kepegawaian"],
          rows: (lecturer.employments || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.sk_cpns_number || "-",
            item.sk_cpns_date || "-",
            item.rank_group || "-",
            item.employment_status || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "kompetensi",
      label: "Kompetensi",
      icon: <Award className="w-5 h-5" />,
      color: "#16A34A",
      subCategories: [
        {
          id: "sertifikasi",
          label: "Sertifikasi",
          entity: "Riwayat Sertifikasi",
          columns: ["No", "Jenis Sertifikasi", "Bidang Studi", "Nomor SK", "Tahun"],
          rows: (lecturer.certifications || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.certification_type || "-",
            item.study_type || "-",
            item.certificate_sk_number || "-",
            item.certification_year || "-",
          ]),
          visible: true,
        },
        {
          id: "tes",
          label: "Tes",
          entity: "Riwayat Tes",
          columns: ["No", "Nama Tes", "Skor", "Penyelenggara", "Tahun"],
          rows: (lecturer.competencyTests || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.test_name || "-",
            item.test_score || "-",
            item.organizer || "-",
            item.year || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "pelaksanaan-pendidikan",
      label: "Pelaksanaan Pendidikan",
      icon: <BookOpen className="w-5 h-5" />,
      color: "#0369A1",
      subCategories: [
        {
          id: "pengajaran",
          label: "Pengajaran",
          entity: "Pengajaran",
          columns: ["No", "Nama Mata Kuliah", "Jenis Mata Kuliah", "Kelas", "Jml Mahasiswa", "SKS"],
          rows: (lecturer.teachings || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.course_name || "-",
            item.course_type || "-",
            item.class || "-",
            item.student_count || "-",
            item.credits || "-",
          ]),
          visible: true,
        },
        {
          id: "bimbingan-mahasiswa",
          label: "Bimbingan Mahasiswa",
          entity: "Bimbingan Mahasiswa",
          columns: ["No", "Semester", "Kategori Kegiatan", "Jenis Bimbingan", "Program Studi"],
          rows: (lecturer.studentSupervisions || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.semester || "-",
            item.activity_category || "-",
            item.supervision_type || "-",
            item.study_program || "-",
          ]),
          visible: true,
        },
        {
          id: "penguji",
          label: "Penguji",
          entity: "Penguji",
          columns: ["No", "Judul Ujian", "Jenis Ujian", "Program Studi"],
          rows: (lecturer.studentExaminations || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.examination_title || "-",
            item.examination_type || "-",
            item.study_program || "-",
          ]),
          visible: true,
        },
        {
          id: "bahan-ajar",
          label: "Bahan Ajar",
          entity: "Bahan Ajar",
          columns: ["No", "Judul", "ISBN", "Tanggal Terbit", "Penerbit"],
          rows: (lecturer.teachingMaterials || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.isbn || "-",
            item.publication_date || item.year || "-",
            item.publisher || "-",
          ]),
          visible: true,
        },
        {
          id: "pengembangan-mahasiswa",
          label: "Pengembangan Mahasiswa",
          entity: "Pengembangan Mahasiswa",
          columns: ["No", "Semester", "Judul Bimbingan", "Jenis Bimbingan", "Program Studi"],
          rows: (lecturer.studentDevelopments || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.semester || "-",
            item.guidance_title || "-",
            item.guidance_type || "-",
            item.study_program || "-",
          ]),
          visible: true,
        },
        {
          id: "visiting-scientist",
          label: "Visiting Scientist",
          entity: "Visiting Scientist",
          columns: ["No", "Perguruan Tinggi Host", "Lama Kegiatan", "Tanggal Pelaksanaan"],
          rows: (lecturer.visitingScientists || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.host_university || item.institution || "-",
            item.duration || "-",
            item.implementation_date || item.year || "-",
          ]),
          visible: true,
        },
        {
          id: "detasering",
          label: "Detasering",
          entity: "Detasering",
          columns: ["No", "Perguruan Tinggi Sasaran", "Kategori Kegiatan", "No SK Penugasan", "Tanggal SK"],
          rows: (lecturer.detaserings || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.target_university || "-",
            item.activity_category || "-",
            item.assignment_decree_number || "-",
            item.decree_date || "-",
          ]),
          visible: true,
        },
        {
          id: "orasi-ilmiah",
          label: "Orasi Ilmiah",
          entity: "Orasi Ilmiah",
          columns: ["No", "Judul Makalah", "Nama Tamu Ilmiah", "Penyelenggara", "Tanggal"],
          rows: (lecturer.academicOrations || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.paper_title || "-",
            item.guest_lecturer_name || "-",
            item.organizer || "-",
            item.activity_date || "-",
          ]),
          visible: true,
        },
        {
          id: "pembimbingan-dosen",
          label: "Pembimbingan Dosen",
          entity: "Pembimbingan Dosen",
          columns: ["No", "Nama Dosen Pembimbing", "Tanggal Mulai", "Tanggal Selesai"],
          rows: (lecturer.lectureMentorings || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.mentor_name || "-",
            item.start_date || "-",
            item.end_date || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "pelaksanaan-penelitian",
      label: "Pelaksanaan Penelitian",
      icon: <FlaskConical className="w-5 h-5" />,
      color: "#B45309",
      subCategories: [
        {
          id: "penelitian",
          label: "Penelitian",
          entity: "Penelitian",
          columns: ["No", "Judul Penelitian", "Bidang Ilmu", "Tahun Pelaksanaan", "Durasi (Bulan)"],
          rows: (lecturer.research || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.scientific_field || "-",
            item.implementation_year || "-",
            item.duration || "-",
          ]),
          visible: true,
        },
        {
          id: "publikasi-karya",
          label: "Publikasi Karya",
          entity: "Publikasi Karya",
          columns: ["No", "Publikasi", "Kuartil", "Nama Jurnal", "Tahun"],
          rows: (lecturer.publications || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.quartile || "-",
            item.venue || item.journal_name || "-",
            item.year || "-",
          ]),
          visible: true,
        },
        {
          id: "hki",
          label: "HKI",
          entity: "HKI",
          columns: ["No", "Judul HKI", "Kuartil", "Nomor Sertifikat", "Tanggal Terbit"],
          rows: (lecturer.hkis || lecturer.hki || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.quartile || "-",
            item.certificate_number || "-",
            item.publish_date || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "pelaksanaan-pengabdian",
      label: "Pelaksanaan Pengabdian",
      icon: <Handshake className="w-5 h-5" />,
      color: "#065F46",
      subCategories: [
        {
          id: "pengabdian",
          label: "Pengabdian",
          entity: "Pengabdian",
          columns: ["No", "Judul Pengabdian", "Bidang Ilmu", "Tahun Pelaksanaan", "Durasi (Bulan)"],
          rows: (lecturer.communityServices || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.scientific_field || "-",
            item.implementation_year || "-",
            item.duration || "-",
          ]),
          visible: true,
        },
        {
          id: "jabatan-struktural",
          label: "Jabatan Struktural",
          entity: "Jabatan Struktural",
          columns: ["No", "Jabatan Struktural", "Nomor SK", "Masa Jabatan"],
          rows: (lecturer.structuralPositions || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.structural_position || "-",
            item.decree_number || "-",
            (item.start_date ? item.start_date + " - " + (item.end_date || "Sekarang") : "-"),
          ]),
          visible: true,
        },
        {
          id: "pembicara",
          label: "Pembicara",
          entity: "Pembicara",
          columns: ["No", "Judul Makalah", "Nama Dosen/Pembicara", "Penyelenggara", "Tanggal Kegiatan"],
          rows: (lecturer.speakers || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.paper_title || "-",
            item.guest_lecturer_name || "-",
            item.organizer || "-",
            item.activity_date || "-",
          ]),
          visible: true,
        },
        {
          id: "pengelola-jurnal",
          label: "Pengelola Jurnal",
          entity: "Pengelola Jurnal",
          columns: ["No", "Nama Jurnal", "Status", "Nomor SK", "Masa Berlaku"],
          rows: (lecturer.journalManagers || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.journal_name || "-",
            (item.is_active ? "Aktif" : "Tidak Aktif") || "-",
            item.decree_number || "-",
            (item.effective_date ? item.effective_date + " - " + (item.end_date || "Sekarang") : "-"),
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "penunjang",
      label: "Penunjang",
      icon: <Star className="w-5 h-5" />,
      color: "#9D174D",
      subCategories: [
        {
          id: "beasiswa",
          label: "Beasiswa",
          entity: "Beasiswa",
          columns: ["No", "Nama Beasiswa", "Sponsor", "Tanggal Mulai", "Tanggal Selesai"],
          rows: (lecturer.scholarships || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.name || "-",
            item.sponsor || item.giver || "-",
            item.start_date || item.year || "-",
            item.end_date || "-",
          ]),
          visible: true,
        },
        {
          id: "anggota-profesi",
          label: "Anggota Profesi",
          entity: "Riwayat Anggota Profesi",
          columns: ["No", "Nama Organisasi", "Peran", "TMT Mulai", "TMT Selesai"],
          rows: (lecturer.professionalMemberships || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.organization_name || "-",
            item.role || "-",
            item.start_date || item.year_joined || "-",
            item.end_date || "-",
          ]),
          visible: true,
        },
        {
          id: "kegiatan-lain",
          label: "Kegiatan Lain",
          entity: "Kegiatan Penunjang Lain",
          columns: ["No", "Nama Kegiatan", "Instansi Penyelenggara", "Nomor SK", "Tanggal Mulai"],
          rows: (lecturer.otherSupportingActivities || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.activity_name || "-",
            item.organizing_institution || "-",
            item.decree_number || "-",
            item.start_date || "-",
          ]),
          visible: true,
        },
        {
          id: "tugas-tambahan",
          label: "Tugas Tambahan",
          entity: "Tugas Tambahan",
          columns: ["No", "Nama Tugas", "Unit Kerja", "Nomor SK", "TMT Mulai", "TMT Selesai"],
          rows: (lecturer.additionalTasks || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.additional_task || "-",
            item.work_unit || "-",
            item.institution || "-",
            item.start_date || "-",
            item.end_date || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "reward",
      label: "Reward",
      icon: <Shield className="w-5 h-5" />,
      color: "#000000ff",
      subCategories: [
        {
          id: "penghargaan",
          label: "Penghargaan",
          entity: "Penghargaan",
          columns: ["No", "Nama Penghargaan", "Tahun", "Penyelenggara"],
          rows: (lecturer.awards || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.award_name || "-",
            item.year || "-",
            item.institution || "-",
          ]),
          visible: true,
        },
        {
          id: "kesejahteraan",
          label: "Kesejahteraan",
          entity: "Kesejahteraan",
          columns: ["No", "Jenis Kesejahteraan", "Penyelenggara", "Tahun"],
          rows: (lecturer.welfares || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.welfare_type || "-",
            item.organizer || "-",
            item.start_year || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "data-dokumen",
      label: "Data Dokumen",
      icon: <FolderOpen className="w-5 h-5" />,
      color: "#000000ff",
      subCategories: [
        {
          id: "riwayat-dokumen-pribadi",
          label: "Riwayat Dokumen Pribadi",
          entity: "Riwayat Dokumen Pribadi",
          columns: ["No", "Jenis Dokumen", "Nomor Dokumen", "Masa Berlaku"],
          rows: (lecturer.identities || []).map((item: any, index: number) => [
            (index + 1).toString(),
            "KTP (NIK)",
            item.nik || "-",
            "-",
          ]),
          visible: true,
        },
      ],
    },
  ];
};

export const mapLecturerToProfileData = (lecturer: any): ProfileData => {
  return {
    name: `${lecturer.title_prefix || ''} ${lecturer.name} ${lecturer.title_suffix || ''}`.trim(),
    imageUrl: lecturer.photo_url || "https://ui-avatars.com/api/?name=" + encodeURIComponent(lecturer.name) + "&background=F3F4F6&color=4B5563",
    university: "Universitas Udayana",
    program: lecturer.faculty || "Fakultas MIPA",
    SiwadaId: lecturer.nidn || lecturer.nip || "-",
    tags: [lecturer.study_program || "Informatika"],
    metrics: { 
      sintaOverall: lecturer.sinta_score_total?.toString() || "0", 
      sinta3Yr: lecturer.sinta_score_3yr?.toString() || "0", 
      scopusHIndex: "0", 
      wosHIndex: "0" 
    },
    activities: [], 
    publications: (lecturer.publications || []).map((pub: any) => ({
      id: pub.id,
      title: pub.title,
      venue: pub.venue || pub.publisher,
      year: parseInt(pub.year || pub.publish_year || new Date().getFullYear()), 
      authorOrder: "1 of 1", 
      type: pub.type || "Journal Article", 
      citations: pub.citation_count || 0,
    })),
  };
};
