import React from "react";
import {
  GraduationCap, Award, BookOpen, FlaskConical,
  Handshake, Star, Shield, FolderOpen,
} from "lucide-react";
import type { Category, ProfileData } from "./types";

export const mapLecturerToCategories = (lecturer: any): Category[] => {
  return [
    {
      id: "kualifikasi",
      label: "Kualifikasi",
      icon: <GraduationCap className="w-5 h-5" />,
      color: "#000000ff",
      subCategories: [
        {
          id: "pendidikan-formal",
          label: "Pendidikan Formal",
          entity: "Riwayat Pendidikan Formal",
          columns: ["No", "Jenjang", "Bidang Ilmu", "Institusi", "Tahun Lulus"],
          rows: (lecturer.educations || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.level || item.degree || item.tingkat || "-",
            item.study_program || item.major || item.program_studi || "-",
            item.university || item.universitas || "-",
            item.graduation_year || item.tahun_lulus || "-",
          ]),
          visible: true,
        },
        {
          id: "diklat",
          label: "Diklat",
          entity: "Diklat",
          columns: ["No", "Nama Diklat", "Jenis Diklat", "Penyelenggara", "Tahun"],
          rows: (lecturer.diklats || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.training_name || item.nama_pelatihan || "-",
            item.training_type || item.jenis_pelatihan || "-",
            item.organizer || item.penyelenggara || "-",
            item.year || item.tahun || "-",
          ]),
          visible: true,
        },
        {
          id: "riwayat-pekerjaan",
          label: "Riwayat Pekerjaan",
          entity: "Riwayat Pekerjaan",
          columns: ["No", "No. SK CPNS", "Tanggal SK CPNS", "Gol. Kepangkatan", "Status Pegawai"],
          rows: (lecturer.employments || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.sk_cpns_number || "-",
            item.sk_cpns_date || "-",
            item.rank_group || item.golongan_kepangkatan || "-",
            item.employment_status || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "kompetensi",
      label: "Kompetensi",
      icon: <Award className="w-5 h-5" />,
      color: "#7C3AED",
      subCategories: [
        {
          id: "sertifikasi",
          label: "Sertifikasi",
          entity: "Sertifikasi",
          columns: ["No", "Jenis Sertifikasi", "Bidang Studi", "Nomor SK/Sertifikat", "Tahun"],
          rows: (lecturer.certifications || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.certification_type || item.jenis_sertifikasi || "-",
            item.study_type || item.jenis_studi || "-",
            item.certificate_sk_number || item.nomor_sk_sertifikat || "-",
            item.certification_year || item.tahun_sertifikasi || "-",
          ]),
          visible: true,
        },
        {
          id: "tes",
          label: "Tes",
          entity: "Tes",
          columns: ["No", "Nama Tes", "Penyelenggara", "Tahun", "Skor"],
          rows: (lecturer.competencyTests || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.test_name || item.nama_tes || "-",
            item.organizer || item.penyelenggara || "-",
            item.year || item.tahun || "-",
            item.test_score || item.skor_tes || item.score || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "pelaksanaan-pendidikan",
      label: "Pelaksanaan Pendidikan",
      icon: <BookOpen className="w-5 h-5" />,
      color: "#0369A1",
      subCategories: [
        {
          id: "pengajaran",
          label: "Pengajaran",
          entity: "Pengajaran",
          columns: ["No", "Mata Kuliah", "Tahun", "Semester", "SKS", "Jumlah Mahasiswa"],
          rows: (lecturer.teachings || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.course_name || "-",
            item.year || "-",
            item.semester || "-",
            item.credits || "-",
            item.total_students || "-",
          ]),
          visible: true,
        },
        {
          id: "bimbingan-mahasiswa",
          label: "Bimbingan Mahasiswa",
          entity: "Bimbingan Mahasiswa",
          columns: ["No", "Nama Mahasiswa", "NIM", "Tingkat", "Judul", "Status"],
          rows: (lecturer.studentSupervisions || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.student_name || "-",
            item.nim || "-",
            item.level || "-",
            item.title || "-",
            item.status || "-",
          ]),
          visible: true,
        },
        {
          id: "pengujian-mahasiswa",
          label: "Pengujian Mahasiswa",
          entity: "Pengujian Mahasiswa",
          columns: ["No", "Nama Mahasiswa", "NIM", "Peran", "Tanggal Ujian"],
          rows: (lecturer.studentExaminations || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.student_name || "-",
            item.nim || "-",
            item.role || "-",
            item.exam_date || "-",
          ]),
          visible: true,
        },
        {
          id: "bahan-ajar",
          label: "Bahan Ajar",
          entity: "Bahan Ajar",
          columns: ["No", "Judul", "Jenis", "Tahun", "Penerbit/Platform"],
          rows: (lecturer.teachingMaterials || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.type || "-",
            item.year || "-",
            item.publisher || "-",
          ]),
          visible: true,
        },
        {
          id: "pembinaan-mahasiswa",
          label: "Pembinaan Mahasiswa",
          entity: "Pembinaan Mahasiswa",
          columns: ["No", "Kegiatan", "Peran", "Tahun", "Keterangan"],
          rows: (lecturer.studentDevelopments || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.activity_name || "-",
            item.role || "-",
            item.year || "-",
            item.description || "-",
          ]),
          visible: true,
        },
        {
          id: "visiting-scientist",
          label: "Visiting Scientist",
          entity: "Visiting Scientist",
          columns: ["No", "Institusi", "Tahun", "Lama (Bulan)"],
          rows: (lecturer.visitingScientists || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.institution || "-",
            item.year || "-",
            item.duration_months || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "pelaksanaan-penelitian",
      label: "Pelaksanaan Penelitian",
      icon: <FlaskConical className="w-5 h-5" />,
      color: "#B45309",
      subCategories: [
        {
          id: "penelitian",
          label: "Penelitian",
          entity: "Penelitian",
          columns: ["No", "Judul Penelitian", "Peran", "Tahun", "Dana"],
          rows: (lecturer.research || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.role || "-",
            item.year || "-",
            item.funding || "-",
          ]),
          visible: true,
        },
        {
          id: "publikasi-karya",
          label: "Publikasi Karya",
          entity: "Publikasi Karya",
          columns: ["No", "Judul", "Jenis", "Penerbit/Venue", "Tahun"],
          rows: (lecturer.publications || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.type || "-",
            item.venue || "-",
            item.year || "-",
          ]),
          visible: true,
        },
        {
          id: "hak-paten-hki",
          label: "Hak Paten/HKI",
          entity: "Paten",
          columns: ["No", "Judul Invensi", "Jenis", "Tahun", "Status"],
          rows: (lecturer.hki || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.type || "-",
            item.year || "-",
            item.status || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "pelaksanaan-pengabdian",
      label: "Pelaksanaan Pengabdian",
      icon: <Handshake className="w-5 h-5" />,
      color: "#065F46",
      subCategories: [
        {
          id: "pengabdian",
          label: "Pengabdian",
          entity: "Pengabdian",
          columns: ["No", "Judul", "Peran", "Mitra", "Tahun"],
          rows: (lecturer.communityServices || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.title || "-",
            item.role || "-",
            item.partner || "-",
            item.year || "-",
          ]),
          visible: true,
        },
        {
          id: "pembicara",
          label: "Pembicara",
          entity: "Pembicara",
          columns: ["No", "Judul Kegiatan", "Peran", "Penyelenggara", "Tahun"],
          rows: (lecturer.speakers || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.event_title || "-",
            item.role || "-",
            item.organizer || "-",
            item.year || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "penunjang",
      label: "Penunjang",
      icon: <Star className="w-5 h-5" />,
      color: "#9D174D",
      subCategories: [
        {
          id: "anggota-profesi",
          label: "Anggota Profesi",
          entity: "Riwayat Anggota Profesi",
          columns: ["No", "Nama Organisasi", "Tingkat", "Tahun Bergabung"],
          rows: (lecturer.professionalMemberships || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.organization_name || "-",
            item.level || "-",
            item.year_joined || "-",
          ]),
          visible: true,
        },
        {
          id: "penghargaan",
          label: "Penghargaan",
          entity: "Penghargaan",
          columns: ["No", "Nama Penghargaan", "Pemberi", "Tahun", "Tingkat"],
          rows: (lecturer.awards || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.name || "-",
            item.giver || "-",
            item.year || "-",
            item.level || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "reward",
      label: "Reward",
      icon: <Shield className="w-5 h-5" />,
      color: "#000000ff",
      subCategories: [
        {
          id: "beasiswa",
          label: "Beasiswa",
          entity: "Beasiswa",
          columns: ["No", "Nama Beasiswa", "Pemberi", "Tahun"],
          rows: (lecturer.scholarships || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.name || "-",
            item.giver || "-",
            item.year || "-",
          ]),
          visible: true,
        },
      ],
    },
    {
      id: "data-dokumen",
      label: "Data Dokumen",
      icon: <FolderOpen className="w-5 h-5" />,
      color: "#000000ff",
      subCategories: [
        {
          id: "riwayat-dokumen-pribadi",
          label: "Riwayat Dokumen Pribadi",
          entity: "Riwayat Dokumen Pribadi",
          columns: ["No", "Jenis Dokumen", "Nomor Dokumen", "Masa Berlaku"],
          rows: (lecturer.identities || []).map((item: any, index: number) => [
            (index + 1).toString(),
            item.type || "-",
            item.number || "-",
            item.valid_until || "-",
          ]),
          visible: true,
        },
      ],
    },
  ];
};

export const mapLecturerToProfileData = (lecturer: any): ProfileData => {
  return {
    name: `${lecturer.title_prefix || ''} ${lecturer.name} ${lecturer.title_suffix || ''}`.trim(),
    imageUrl: lecturer.photo_url || "https://ui-avatars.com/api/?name=" + encodeURIComponent(lecturer.name) + "&background=F3F4F6&color=4B5563",
    university: "Universitas Udayana",
    program: lecturer.faculty || "Fakultas MIPA",
    SiwadaId: lecturer.nidn || lecturer.nip || "-",
    tags: [lecturer.study_program || "Informatika"],
    metrics: { 
      sintaOverall: lecturer.sinta_score_total?.toString() || "0", 
      sinta3Yr: lecturer.sinta_score_3yr?.toString() || "0", 
      scopusHIndex: "0", 
      wosHIndex: "0" 
    },
    activities: [], 
    publications: (lecturer.publications || []).map((pub: any) => ({
      id: pub.id,
      title: pub.title,
      venue: pub.venue || pub.publisher,
      year: parseInt(pub.year || pub.publish_year || new Date().getFullYear()), 
      authorOrder: "1 of 1", 
      type: pub.type || "Journal Article", 
      citations: pub.citation_count || 0,
    })),
  };
};
